// Exports Foundry ABIs into packages/shared/src/abi as typed `as const` modules.
// Run after any contract change: `node scripts/export-abis.mjs`
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const out = join(root, 'packages/shared/src/abi')
mkdirSync(out, { recursive: true })

const contracts = [
  ['AdInventoryRegistry', 'AdInventoryRegistry.sol'],
  ['ENSv2AuthorizationAdapter', 'ENSv2AuthorizationAdapter.sol'],
  ['ProofAdsMarket', 'ProofAdsMarket.sol'],
  ['ProofAdsSettlementReceiver', 'ProofAdsSettlementReceiver.sol'],
  ['MockUSDC', 'MockUSDC.sol'],
  ['PermissionedRegistry', 'PermissionedRegistry.sol'],
  ['PermissionedResolver', 'PermissionedResolver.sol'],
  ['LabelStore', 'LabelStore.sol'],
]

const index = []
for (const [name, file] of contracts) {
  const artifact = JSON.parse(readFileSync(join(root, 'contracts/out', file, `${name}.json`), 'utf8'))
  const body = `// Generated by scripts/export-abis.mjs — do not edit by hand.\nexport const ${name}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const\n`
  writeFileSync(join(out, `${name}.ts`), body)
  index.push(`export { ${name}Abi } from './${name}'`)
}
writeFileSync(join(out, 'index.ts'), `// Generated by scripts/export-abis.mjs — do not edit by hand.\n${index.join('\n')}\n`)
console.log(`Exported ${contracts.length} ABIs to packages/shared/src/abi`)
