/**
 * Turns a Foundry deployment JSON into apps/web/.env.local, so the UI never hardcodes an
 * address. Run after `pnpm deploy:local` or `pnpm deploy:sepolia`.
 *
 *   node scripts/write-web-env.mjs local   -> reads contracts/deployments/local.json
 *   node scripts/write-web-env.mjs sepolia -> reads contracts/deployments/sepolia.json
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const network = process.argv[2] ?? 'local'
const deployment = JSON.parse(readFileSync(join(root, `contracts/deployments/${network}.json`), 'utf8'))

const apiUrl = process.env.API_PUBLIC_URL ?? 'http://127.0.0.1:8787'
const rpcUrl =
	process.env.WEB_RPC_URL ?? (network === 'local' ? 'http://127.0.0.1:8545' : process.env.SEPOLIA_RPC_URL ?? '')

const lines = [
	`# Generated by scripts/write-web-env.mjs from contracts/deployments/${network}.json`,
	`NEXT_PUBLIC_CHAIN_ID=${deployment.chainId}`,
	`NEXT_PUBLIC_RPC_URL=${rpcUrl}`,
	`NEXT_PUBLIC_API_URL=${apiUrl}`,
	`NEXT_PUBLIC_PUBLISHER_NAME=${deployment.publisherName}`,
	`NEXT_PUBLIC_AD_INVENTORY_REGISTRY=${deployment.adInventoryRegistry}`,
	`NEXT_PUBLIC_AUTHORIZATION_ADAPTER=${deployment.authorizationAdapter}`,
	`NEXT_PUBLIC_MARKET=${deployment.market}`,
	`NEXT_PUBLIC_SETTLEMENT_RECEIVER=${deployment.settlementReceiver}`,
	`NEXT_PUBLIC_USDC=${deployment.usdc}`,
	`NEXT_PUBLIC_PUBLISHER_RESOLVER=${deployment.publisherResolver}`,
	`NEXT_PUBLIC_LABEL_STORE=${deployment.labelStore}`,
	`NEXT_PUBLIC_ROOT_REGISTRY=${deployment.rootRegistry}`,
	`NEXT_PUBLIC_SLOTS=hero,sidebar`,
	'',
]
writeFileSync(join(root, 'apps/web/.env.local'), lines.join('\n'))
console.log(`Wrote apps/web/.env.local for ${network} (chainId ${deployment.chainId})`)
